# Generated by Django 3.1 on 2020-08-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa restauracji')),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Składniki')),
                ('price', models.IntegerField(default=0, verbose_name='Cena za dodatek')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa dania/napoju')),
                ('price', models.IntegerField(verbose_name='Cena za danie')),
                ('category', models.IntegerField(choices=[(4, 'drinks'), (2, 'lunch'), (6, 'other'), (3, 'starters'), (5, 'alcohol'), (1, 'dinner')], verbose_name='Kategoria dania')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('toppings', models.ManyToManyField(related_name='dish_toppings_set', to='restaurant.Toppings')),
            ],
        ),
    ]
