# Generated by Django 3.1 on 2020-08-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa miasta'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.IntegerField(choices=[(3, 'starters'), (5, 'alcohol'), (4, 'drinks'), (6, 'other'), (2, 'lunch'), (1, 'dinner')], verbose_name='Kategoria dania'),
        ),
    ]
