# Generated by Django 3.1 on 2020-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200817_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default_picture/default.JPG', upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.IntegerField(choices=[(5, 'alcohol'), (6, 'other'), (3, 'starters'), (1, 'dinner'), (2, 'lunch'), (4, 'drinks')], verbose_name='Kategoria dania'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='dish_toppings_set', to='restaurant.Toppings'),
        ),
    ]
