# Generated by Django 3.1 on 2020-08-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_auto_20200819_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.IntegerField(choices=[(6, 'other'), (2, 'lunch'), (5, 'alcohol'), (1, 'dinner'), (3, 'starters'), (4, 'drinks')], verbose_name='Kategoria dania'),
        ),
    ]
