# Generated by Django 3.1 on 2020-10-05 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0004_auto_20200819_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.IntegerField(choices=[(2, 'lunch'), (3, 'starters'), (1, 'dinner'), (5, 'alcohol'), (4, 'drinks'), (6, 'other')], verbose_name='Kategoria dania'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
